apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: container-registry
  values:
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.blanktorious.com
        tls:
          enabled: false
        controller: default
        className: traefik
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
#          traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    externalURL: https://harbor.blanktorious.com
#    harborAdminPassword: harbor123
    persistence:
      persistentVolumeClaim:
        registry:
          size: 10Gi
        chartmuseum:
          enabled: false
    notary:
      enabled: false
    trivy:
      enabled: true