apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: container-registry
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.blanktorious.com
        className: traefik
        annotations:
#          ingress.kubernetes.io/ssl-redirect: "true"
#          traefik.ingress.kubernetes.io/router.entrypoints: websecure
    externalURL: https://harbor.blanktorious.com
    harborAdminPassword: '{{ .Values.harborAdminPassword }}'
    persistence:
      persistentVolumeClaim:
        registry:
          size: 10Gi