apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.16.2"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: container-registry
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    expose:
      type: ingress
      tls:
        enabled: false
      ingress:
        hosts:
          core: harbor.blanktorious.com
        className: traefik
        annotations:
#          ingress.kubernetes.io/ssl-redirect: "false"
#          traefik.ingress.kubernetes.io/router.entrypoints: web
    externalURL: https://harbor.blanktorious.com
#    harborAdminPassword: "Harbor123"
    persistence:
      persistentVolumeClaim:
        registry:
          size: 10Gi