apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio

    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: my-portfolio
          image: blanktorious/my-port-v1:latest
          ports:
            - containerPort: 8081
          
          volumeMounts:
            - name: my-emptydir-volume
              mountPath: /etc/my-portfolio/data
          
          securityContext:
            allowPrivilegeEsclation: false
      # volumes:
      #   - name: my-portfolio-data
      #     persistentVolumeClaim:
      #       claimName: my-portfolio-pv-claim
      volumes:
      - name: my-emptydir-volume
        emptyDir: {}