apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - cloudflare.yaml
  - /secrets/cloudflared-secret.yaml
  - /secrets/linkding-secret.yaml
