apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:fqn2xqoqtgrEzBLIa/fRCJeJEB/keHRwaRyxAAj0JQcXVsf0+318J1Zg8gCpfQ+f8rmeE6fs/fSIKLrTlX2lNEYJ8WJH6Bk2pajy833iLprMMVDdLv+6yT14ALrMswsTl5U6PeZPPpLNfkpuLT2mmKPIS0JK9nPR/g31rb6zlJs8A/eYnvGgAEJW86Al0AgggdHTV63ldGKkhkmVwgn7sM7TCXD9aiSy5GzNITDxJ39AhyDcX2GxxRJsvOFuwwwWB+mFHmlumvu2ogj2nGYhlg99z9LIKuGpqYH7Yb7yOtxEGvBG82mafyR5ooA=,iv:fORPlTai5lWY5AgT8gF7fNUdehfvxc6VkAxRUaIe5mk=,tag:CAiIFdgqoVQouQ3bp+rmIQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1faefyw3avmqjnap7cmqh5yayuu06v9rtaagc9fc6strytn275ywqvy0k6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N0w4WVZoV2xqYnNFUDg0
            VGEyZUF1ZVdFQ2xiMWhUN1hIbFM1dmZucGtjCk0zanBiV3R2WHBsaS80VHNleEkv
            QjJBUlRqdmFMZkV2eTQxMDFCcERoSkUKLS0tIHZJR1NaeHhIdzNBcFd6amF6MzZM
            VDdHZGhLc1pUc0lSQVY1TU53c1FvRDQKNKgwTCTPV/89BjOl1Z7/NvbTrKbceBR9
            Ibb7onCZCqlrDQDswSnbX+f1r702VcpwP/3v5Fs3P88HMJSVliai3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T16:08:00Z"
    mac: ENC[AES256_GCM,data:0wU4kC2OriiEMQerXp0Jf2ryZT+GsV5LHMGKo4FYu6Wo2isl6i9Cvq1owj9eaxeefqJO4lYg5R6aD4vhkXz50ds06N1E/WFvTrG07uT0Dl7tfrCv5FG3jeQfeLQlGVZ0gsxQOkr+m1hE/D99wPiLDuux+3lH0z4HQhYSFFcfJf8=,iv:rc1/GlmDpVqLte9mxTWH0PZtrlhCbvXPGY4M2Tfdoi4=,tag:cBuQ2Stt49gPT2V470Kmsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
