#Service
apiVersion: v1
kind: Service
metadata:
  name: private-registry-service
  namespace: docker-registry
spec:
  selector:
    app: private-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # Or LoadBalancer if you have an external load balancer
